### ISSUE TITLE
Social Distance Detector 내용 추가

### ISSUE THREAD

**Issue by syohnet** [dhrim/pis_study#11]
(2020.10.08 스터디 발표) Social Distance Detector 기존 자료에서 한글 주석,참고 레퍼런스 보완

**Comment by syohnet** [comment]
파일 관리 규칙이 파악되지 않아 이전 파일 원본 보존을 위해, 아래와 같이 작업합니다.
- version 1.1 로 새 파일 commit
- README.md 에 v1_1 파일 링크로 수정

**Comment by dhrim** [comment]
신경써 주셔서 감사합니다. 업데이트 감사요.
